### ISSUE TITLE
Using the SDK

### ISSUE THREAD

**Issue by chakkit** [oraichain/oraidex-sdk#11]
I'd like to run the SDK as a standlone engine and using my python script to interact with the SDK, especially feeding token rates, order booking and swapping the tokens.

Is it possible, if so, how to do it?

Also, I see your coding required "dotenv/config" and have no idea about the config.

If it possible, can you make a doc shows how to use the SDK step by step.

**Comment by ducphamle2** [comment]
Hi. This SDK is purposefully built for JS / TS only, do you still want us to support you with the doc?

**Comment by tucq88** [comment]
Close due to lack of activity
